language: erlang
otp_release:
  - 19.3
install:
  - ./rebar3 update
  - make
before_script:
  - epmd -daemon
  - sudo apt-get install shellcheck
script:
  - make test
  - make xref
  - make dialyzer
  - make lint
matrix:
  fast_finish: true
notifications:
  slack: haslab:jhAnACJzswFtYwKXpbZzjbFq
  email: false
sudo: true
