sudo: false
language: erlang
otp_release:
  - 19.3
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck
install:
  - ./rebar3 update
  - make
before_script:
  - epmd -daemon
script:
  - make test
  - make xref
  - make dialyzer
  - make lint
  - make shell-lint
matrix:
  fast_finish: true
notifications:
  slack: haslab:jhAnACJzswFtYwKXpbZzjbFq
  email: false
